### ISSUE TITLE
Tab closing stops after 1,000 tabs

### ISSUE THREAD

**Issue by jhamilton09** [mukunku/Tab-Close-Gold#14]
I'm using a script to open a bunch of obscured links and then this great extension closes them if they don't match the subset I'm looking for. If I don't close and restart Chrome after 1,000 tabs opened, they suddenly stop getting closed by the extension.

I put a pause in my script every 1000 links to get what I need, restart Chrome, and start the next batch. Any idea if there's a limit to the extension or some way I can clear this hurdle?

Thanks!

**Comment by jhamilton09** [comment]
Doing some more testing, I tried resetting the hit count to see if it was a storage limit causing it. Before the issue happens, I can reset the hit count without error in the Options page. After the issue happens, I get "Could not save configuration!" when just clicking "Reset hits".

**Comment by leodoi3** [comment]
I have the same problem but it stops after 100 tabs

**Comment by mukunku** [comment]
Hey @jhamilton09 , @leodoi3 

Can you try the following steps please. There is a secret panel to switch from Cloud storage to Local storage. That might help solve your issues.

1. Make a backup of all your configuration by exporting it and saving it to a file somewhere, just in case.
   ![image](https://github.com/mukunku/Tab-Close-Gold/assets/4502154/d0af4a6f-4637-44a5-9eb8-9fd77b577a5e)
2.  Go to the Tab Close Gold options page and hit F12 to open the developer console
3. In the developer console locate the html element with the id `super-secret-admin-panel` 
4. Remove the `display: none;` style to make the secret panel visible.
   ![image](https://github.com/mukunku/Tab-Close-Gold/assets/4502154/e3f2cdc4-c488-45e8-a4e0-abd7e4568e95)
5. You will see a now drop down appear above the storage bar in the bottom left. Switch from `Cloud` to `Local` storage. 
   ![image](https://github.com/mukunku/Tab-Close-Gold/assets/4502154/b2bba5e3-8890-4625-9286-3c610d7c472d)
6. Your settings should automatically get copied to local storage instead of cloud storage. 
   * You can confirm this by refreshing the options page and revealing the secret panel again and confirming it is still set to `Local`.
   * You can also confirm this by looking the storage usage percentage. It should go down on Local storage since Local storage is virtually limitless.

Let me know if this fixes the issue for you. If so, I can maybe reveal that panel so everyone can use it.

**Comment by leodoi3** [comment]
@mukunku Unfortunately it did not work for me.

**Comment by mukunku** [comment]
@leodoi3 , @jhamilton09 

I just released version 3.0.0.0. Can you folks test that version out?

I completely re-wrote the tab closing engine so hopefully it can handle whatever you throw at it now. 

If you still experience any issues feel free to re-open this ticket.
